### ISSUE TITLE
Graph Issues & Improvements

### ISSUE THREAD

**Issue by mchlp** [brandongit2/math#15]
Bugs:
- [x] Numbers not aligned with axis when xScale is not equal to yScale
- [x] Gridline numbers are too long
![image](https://user-images.githubusercontent.com/22804087/38903666-fa6b80f6-4273-11e8-851b-5d5f97b67c84.png)
- [x] Gridline numbers overflowing
![image](https://user-images.githubusercontent.com/22804087/39087225-068f2aa4-456c-11e8-9db5-4964081751d7.png)
- [x] Scale numbers disappeared after 1e-10

To Do:
- [x] Scale the graph by scrolling
- [x] Pan the graph by clicking and dragging
- [ ] Animate scrolling -  **Transferred to #17**
- [ ] Inertia when panning -  **Transferred to #17**
- [ ] Zoom in/out on mouse position -  **Transferred to #17**
- [x] Determine best interval between major gridlines
- [x] Adjust major gridlines so that they appear at multiples of 1/2/5 x 10<sup>n</sup>
- [x] Change the number of minor gridlines between major gridlines depending on the interval
 - 5 minor for interval of 1
 - 4 minor for interval of 2
 - 5 minor for interval of 5
- [ ] Scale numbers for when the X or Y axis is not visible  -  **Transferred to #17**

Testing/Verify:
- [x] Ensure getNearestMultiple() function is accurate
